# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 滕家熙的博客
email: tengjiaxi@126.com
description: > # this means to ignore newlines until "baseurl:"
  大家好，我叫滕家熙，这是我的个人网站。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tengjiaxi.com" # the base hostname & protocol for your site
twitter_username: tengjiaxi
github_username:  tengjiaxi

# Build settings
markdown: kramdown
